CREATE TABLE IF NOT EXISTS ledger (
  id BIGINT NOT NULL AUTO_INCREMENT,
  date VARCHAR(20) NOT NULL,
  type VARCHAR(20) NOT NULL,
  amount DECIMAL(18,2) NOT NULL,
  description VARCHAR(255) DEFAULT NULL,
  category VARCHAR(50) DEFAULT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS holding (
  id BIGINT NOT NULL AUTO_INCREMENT,
  big_type VARCHAR(20) NOT NULL,
  name VARCHAR(100) NOT NULL,
  amount DECIMAL(18,2) NOT NULL,
  monthly_cashflow DECIMAL(18,2) DEFAULT NULL,
  note VARCHAR(255) DEFAULT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS watchlist (
  id BIGINT NOT NULL AUTO_INCREMENT,
  type VARCHAR(20) NOT NULL,
  name VARCHAR(100) NOT NULL,
  code VARCHAR(30) DEFAULT NULL,
  category VARCHAR(50) DEFAULT NULL,
  cost DECIMAL(18,2) DEFAULT NULL,
  amount DECIMAL(18,2) DEFAULT NULL,
  target_price DECIMAL(18,2) DEFAULT NULL,
  note VARCHAR(255) DEFAULT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS decision_log (
  id BIGINT NOT NULL AUTO_INCREMENT,
  scene VARCHAR(50) DEFAULT NULL,
  question TEXT NOT NULL,
  answer LONGTEXT,
  verdict VARCHAR(20) DEFAULT NULL,
  model VARCHAR(50) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_scene_created (scene, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
